name: simple_note_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - packages/*
  - apps/*

scripts:
  analyze:
    exec: dart analyze

  get:
    run: melos exec -c 1  -- "flutter pub get"

  clean:
     run: melos exec -c 1  -- "flutter clean"