name: Flutter CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: stable

      # Get dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Analyze code
      - name: Run Flutter Analyze
        run: flutter analyze

      # Run tests
      - name: Run Flutter Tests
        run: flutter test --coverage
