name: Flutter CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run Flutter Tests (Monorepo)
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: stable

      # Setup Melos
      - name: Install Melos
        run: dart pub global activate melos

      # Bootstrap all packages (install deps + link local packages)
      - name: Melos bootstrap
        run: melos bootstrap --sdk-path=$FLUTTER_ROOT

      # Run analysis for all packages
      - name: Analyze
        run: melos run analyze --no-select --sdk-path=$FLUTTER_ROOT
        continue-on-error: false

      # Run all tests across packages
      - name: Run Tests
        run: melos run test --no-select --sdk-path=$FLUTTER_ROOT
